import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const ROOT = '/home/sandbox/blastline';
const MIME = new Map([['.css','text/css'],['.html','text/html'],['.js','text/javascript'],['.mjs','text/javascript'],['.webp','image/webp'],['.png','image/png']]);
const server = http.createServer((req,res)=>{ const p=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/,''); const f=path.resolve(ROOT,p===''?'index.html':p); fs.readFile(f,(e,d)=>{ if(e){res.writeHead(404);return res.end();} res.writeHead(200,{'Cache-Control':'no-store','Content-Type':MIME.get(path.extname(f))||'application/octet-stream'}); res.end(d); }); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const port = server.address().port;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load' });
await page.waitForTimeout(800);
await page.screenshot({ path: '/home/sandbox/c6-evidence/v2-ftue-home.png' });
await page.tap('#playBtn');
await page.waitForTimeout(1800);
await page.screenshot({ path: '/home/sandbox/c6-evidence/v2-ftue-t2.png' });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/home/sandbox/c6-evidence/v2-ftue-t4.png' });
await page.waitForTimeout(4000);
await page.screenshot({ path: '/home/sandbox/c6-evidence/v2-ftue-t8.png' });
await browser.close(); server.close(); process.exit(0);
