import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const ROOT = '/home/sandbox/blastline';
const MIME = new Map([['.css','text/css'],['.html','text/html'],['.js','text/javascript'],['.mjs','text/javascript'],['.webp','image/webp'],['.png','image/png']]);
const server = http.createServer((req,res)=>{ const p=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/,''); const f=path.resolve(ROOT,p===''?'index.html':p); fs.readFile(f,(e,d)=>{ if(e){res.writeHead(404);return res.end();} res.writeHead(200,{'Cache-Control':'no-store','Content-Type':MIME.get(path.extname(f))||'application/octet-stream'}); res.end(d); }); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const port = server.address().port;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto(`http://127.0.0.1:${port}/?qa`, { waitUntil: 'load' });
await page.waitForTimeout(500);
const state = async () => page.evaluate(() => ({ icon: document.getElementById('muteBtn').textContent, pressed: document.getElementById('muteBtn').getAttribute('aria-pressed'), stored: localStorage.getItem('blastline.muted.v1') }));
const s0 = await state();
await page.evaluate(() => document.getElementById('muteBtn').click()); await page.waitForTimeout(150);
const s1 = await state();
await page.reload({ waitUntil: 'load' }); await page.waitForTimeout(500);
const s2 = await state();
await page.evaluate(() => document.getElementById('muteBtn').click()); await page.waitForTimeout(150);
await page.reload({ waitUntil: 'load' }); await page.waitForTimeout(500);
const s3 = await state();
console.log('MUTE', JSON.stringify({ initial: s0, afterClick: s1, afterReload: s2, toggledBackReloaded: s3 }));
await browser.close(); server.close(); process.exit(0);
