import fs from'node:fs';
const path='src/game.js';let s=fs.readFileSync(path,'utf8');
function r(from,to,label){if(s.includes(to))return;if(!s.includes(from))throw new Error(`missing ${label}`);s=s.replace(from,to)}
r(`  const left=worldToScreen(gate.x-gate.w/2,gate.y);\n  const right=worldToScreen(gate.x+gate.w/2,gate.y);\n  const panelW=Math.max(18,right.x-left.x);\n  const depth=clamp((gate.y+.04)/1.04,0,1);\n  const panelH=Math.min(H*.086,Math.max(18,panelW*.62));\n  const frameH=panelH*1.34;`,
`  const rawLeft=worldToScreen(gate.x-gate.w/2,gate.y);\n  const rawRight=worldToScreen(gate.x+gate.w/2,gate.y);\n  const rawW=rawRight.x-rawLeft.x;\n  const visualHalf=rawW*.60;\n  const left={...rawLeft,x:center.x-visualHalf};\n  const right={...rawRight,x:center.x+visualHalf};\n  const panelW=Math.max(26,right.x-left.x);\n  const depth=clamp((gate.y+.04)/1.04,0,1);\n  const panelH=Math.min(H*.132,Math.max(27,panelW*.88));\n  const frameH=panelH*1.58;`,
'gate proportions');
r(`    const bw = Math.min(360, W*0.42), bh = 12;\n    ctx.fillStyle='rgba(0,0,0,.35)'; ctx.fillRect(W/2-bw/2, H*0.14, bw, bh);\n    ctx.fillStyle='#ff5959'; ctx.fillRect(W/2-bw/2, H*0.14, bw * clamp(boss.hp / boss.maxHp,0,1), bh);\n    ctx.fillStyle='#fff'; ctx.font='900 18px system-ui'; ctx.textAlign='center'; ctx.fillText('BOSS', W/2, H*0.14 - 8);`,
`    const bw = Math.min(330, W*0.46), bh = Math.max(9,Math.min(12,H*.014));\n    const by=H*.105;\n    ctx.fillStyle='rgba(8,17,23,.78)';ctx.beginPath();ctx.roundRect(W/2-bw/2-4,by-4,bw+8,bh+8,7);ctx.fill();\n    ctx.fillStyle='#5c2228';ctx.beginPath();ctx.roundRect(W/2-bw/2,by,bw,bh,4);ctx.fill();\n    const bossFill=ctx.createLinearGradient(W/2-bw/2,0,W/2+bw/2,0);bossFill.addColorStop(0,'#ff704f');bossFill.addColorStop(1,'#d92f3c');ctx.fillStyle=bossFill;ctx.beginPath();ctx.roundRect(W/2-bw/2,by,bw*clamp(boss.hp/boss.maxHp,0,1),bh,4);ctx.fill();\n    ctx.fillStyle='#fff';ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.fillText('BOSS',W/2,by-8);`,
'boss health');
fs.writeFileSync(path,s);console.log('pass 2 applied');
