import {LEVELS,META_UPGRADES,mulberry32,clamp,formatScore,applyMetaUpgrade,gateEffect,gateLabel,pickUnique,makeGatePair,initialPlayer} from './core.mjs';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d',{alpha:false});
const menu=document.querySelector('#menu'),upgradePanel=document.querySelector('#upgradePanel'),gameOverPanel=document.querySelector('#gameOverPanel'),hud=document.querySelector('#hud');
const playBtn=document.querySelector('#playBtn'),retryBtn=document.querySelector('#retryBtn'),soundBtn=document.querySelector('#soundBtn'),cards=document.querySelector('#upgradeCards'),telemetry=document.querySelector('#telemetry');
const levelLabel=document.querySelector('#levelLabel'),levelName=document.querySelector('#levelName'),scoreLabel=document.querySelector('#scoreLabel'),bestLabel=document.querySelector('#bestLabel'),bar=document.querySelector('#levelBar i');
const query=new URLSearchParams(location.search);const captureMode=query.get('capture')==='1';let captureFrames=0;
let W=innerWidth,H=innerHeight,dpr=1,last=0,acc=0,state='menu',levelIndex=0,levelTime=0,score=0,best=Number(localStorage.getItem('blastline-best')||0),rng=Math.random,player=initialPlayer();
let bullets=[],enemies=[],gates=[],particles=[],texts=[],boss=null,spawnClock=0,gateClock=3,frenzy=0,frenzyTime=0,shake=0,keys={},pointerX=.5,pointerActive=false,audio=null,sound=true,runSeed=Date.now()>>>0;
bestLabel.textContent=formatScore(best);
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize,{passive:true});resize();
function setState(s){state=s;telemetry.dataset.state=s;menu.classList.toggle('visible',s==='menu');upgradePanel.classList.toggle('visible',s==='upgrade');gameOverPanel.classList.toggle('visible',s==='over');hud.classList.toggle('visible',s==='playing')}
function initAudio(){if(audio||!sound)return;audio=new (window.AudioContext||window.webkitAudioContext)()}
function tone(freq=.2,dur=.05,type='square',vol=.035){if(!audio||!sound)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function startRun(seed=Date.now()>>>0){initAudio();runSeed=seed;rng=mulberry32(seed);levelIndex=0;score=0;player=initialPlayer();startLevel()}
function startLevel(){bullets=[];enemies=[];gates=[];particles=[];texts=[];boss=null;levelTime=0;spawnClock=.7;gateClock=2.2;frenzy=0;frenzyTime=0;player.x=.5;setState('playing');updateHud();tone(420,.12,'sine',.05)}
function updateHud(){const L=LEVELS[Math.min(levelIndex,LEVELS.length-1)];levelLabel.textContent=`LEVEL ${levelIndex+1}`;levelName.textContent=L?.name||'ENDLESS';scoreLabel.textContent=formatScore(score);bestLabel.textContent=formatScore(Math.max(best,score));const p=boss?1:clamp(levelTime/(L?.duration||60),0,1);bar.style.width=`${p*100}%`;telemetry.dataset.level=String(levelIndex+1);telemetry.dataset.score=String(Math.floor(score));telemetry.dataset.x=player.x.toFixed(3);telemetry.dataset.troops=String(player.troops);telemetry.dataset.armor=String(player.armor)}
function endRun(){setState('over');best=Math.max(best,Math.floor(score));localStorage.setItem('blastline-best',best);document.querySelector('#finalScore').textContent=formatScore(score);document.querySelector('#finalLevel').textContent=levelIndex+1;document.querySelector('#finalBest').textContent=formatScore(best);tone(95,.35,'sawtooth',.05)}
function levelClear(){score+=1000*(levelIndex+1);setState('upgrade');const choices=pickUnique(rng,META_UPGRADES,3);cards.innerHTML='';for(const u of choices){const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<strong>${u.icon}</strong><b>${u.title}</b><span>${u.desc}</span>`;b.onclick=()=>{player=applyMetaUpgrade(player,u.id);levelIndex++;startLevel()};cards.appendChild(b)}tone(660,.12,'sine',.05);setTimeout(()=>tone(880,.14,'sine',.04),120)}
function spawnEnemy(){const L=LEVELS[Math.min(levelIndex,LEVELS.length-1)],r=18+Math.min(10,levelIndex*2),elite=rng()<Math.min(.28,.05+levelIndex*.04);enemies.push({x:.08+rng()*.84,y:-.06,hp:(elite?3.2:1)*L.hp,maxHp:(elite?3.2:1)*L.hp,speed:(.052+rng()*.025)*L.speed,r:r*(elite?1.28:1),elite,phase:rng()*6.28})}
function spawnGatePair(){const pair=makeGatePair(rng,levelIndex),y=.17,w=Math.min(.33,390/W),gap=Math.max(.06,24/W),offset=w/2+gap/2;gates.push({...pair[0],x:.5-offset,y,w,h:.105,progress:0,active:false,passed:false});gates.push({...pair[1],x:.5+offset,y,w,h:.105,progress:0,active:false,passed:false})}
function spawnBoss(){const L=LEVELS[Math.min(levelIndex,LEVELS.length-1)];boss={x:.5,y:-.12,hp:L.boss,maxHp:L.boss,r:Math.min(W,H)*.075,name:L.bossName,shot:0};enemies=[];gates=[];tone(120,.4,'sawtooth',.04)}
function fire(){const count=player.projectiles,spread=Math.min(.18,.035*(count-1));for(let i=0;i<count;i++){const f=count===1?0:(i/(count-1)-.5)*spread;bullets.push({x:player.x+f*.2,y:.78,vx:f,vy:-.72*player.bulletSpeed,damage:player.damage})}tone(frenzyTime>0?260:210,.025,'square',.012)}
function hitBurst(x,y,color='#ff6d70',n=7){for(let i=0;i<n;i++)particles.push({x,y,vx:(rng()-.5)*.28,vy:(rng()-.5)*.28,life:.25+rng()*.25,size:2+rng()*4,color})}
function floatText(x,y,text,color='#fff',size=18){texts.push({x,y,text,color,size,life:.8})}
function breach(e){if(player.armor>0){player.armor--;floatText(e.x,.8,'ARMOR BLOCK','#67d6ff',18);tone(150,.08,'square',.04)}else{const loss=e.elite?5:2;player.troops-=loss;floatText(e.x,.82,`-${loss} TROOPS`,'#ff7777',20);shake=Math.max(shake,7);tone(85,.11,'sawtooth',.04);if(player.troops<=0)endRun()}}
function applyGate(g){if(!g.active)return;player=gateEffect(player,g);floatText(g.x,.74,gateLabel(g),'#78f1b1',18);score+=125;tone(720,.07,'sine',.03)}
function update(dt){if(state!=='playing')return;const L=LEVELS[Math.min(levelIndex,LEVELS.length-1)];levelTime+=dt;spawnClock-=dt;gateClock-=dt;if(frenzyTime>0)frenzyTime-=dt;const speedBoost=frenzyTime>0?1.65:1;const move=(keys.ArrowLeft||keys.a?-1:0)+(keys.ArrowRight||keys.d?1:0);if(move)pointerX=clamp(pointerX+move*dt*.72,.06,.94);player.x+=(pointerX-player.x)*Math.min(1,dt*10);
  acc+=dt;const interval=1/(player.fireRate*speedBoost);while(acc>interval){acc-=interval;fire()}
  if(!boss&&levelTime<L.duration&&spawnClock<=0){spawnEnemy();if(rng()<.22+levelIndex*.035)spawnEnemy();spawnClock=L.spawn*(.78+rng()*.5)}
  if(!boss&&levelTime<L.duration-5&&gateClock<=0){spawnGatePair();gateClock=7.2-rng()*1.4}
  if(!boss&&levelTime>=L.duration)spawnBoss();
  for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt}
  for(const e of enemies){e.y+=e.speed*dt;e.x+=Math.sin(levelTime*1.7+e.phase)*dt*.009}
  for(const g of gates)g.y+=dt*.105;
  if(boss){boss.y+=(boss.y<.19?.16:0)*dt;boss.shot-=dt;if(boss.shot<=0&&boss.y>=.18){boss.shot=.78-Math.min(.22,levelIndex*.03);const shots=2+Math.floor(levelIndex/2);for(let i=0;i<shots;i++)enemies.push({x:clamp(boss.x+(rng()-.5)*.5,.08,.92),y:boss.y+.05,hp:L.hp*.65,maxHp:L.hp*.65,speed:.09*L.speed,r:14,elite:false,phase:rng()*6.28})}}
  for(const b of bullets){if(b.dead)continue;for(const g of gates){if(g.passed||b.y<g.y-g.h/2||b.y>g.y+g.h/2||Math.abs(b.x-g.x)>g.w/2)continue;b.dead=true;g.progress+=b.damage;if(!g.active&&g.progress>=g.charge){g.active=true;hitBurst(g.x,g.y,'#5fffb1',12);tone(540,.05,'sine',.03)}break}if(b.dead)continue;if(boss&&Math.hypot((b.x-boss.x)*W,(b.y-boss.y)*H)<boss.r){b.dead=true;boss.hp-=b.damage;hitBurst(b.x,b.y,'#ff686c',3);score+=2;if(boss.hp<=0){hitBurst(boss.x,boss.y,'#ffb04a',38);boss=null;score+=2500*(levelIndex+1);levelClear();return}}if(b.dead)continue;for(const e of enemies){if(e.dead)continue;const dx=(b.x-e.x)*W,dy=(b.y-e.y)*H;if(dx*dx+dy*dy<e.r*e.r){b.dead=true;e.hp-=b.damage;if(e.hp<=0){e.dead=true;score+=e.elite?55:18;frenzy=Math.min(12,frenzy+(e.elite?3:1));hitBurst(e.x,e.y,e.elite?'#ffb04a':'#ff656b',e.elite?12:6);if(frenzy>=12){frenzy=0;frenzyTime=5;floatText(.5,.5,'FRENZY!','#67ddff',32);tone(900,.08,'square',.035)}}break}}}
  for(const g of gates){if(!g.passed&&g.y>=.77){g.passed=true;if(Math.abs(player.x-g.x)<g.w*.5)applyGate(g)}
  for(const e of enemies){if(!e.dead&&e.y>.79){e.dead=true;breach(e);if(state!=='playing')return}}
  bullets=bullets.filter(b=>!b.dead&&b.y>-.1&&b.x>-.1&&b.x<1.1);enemies=enemies.filter(e=>!e.dead&&e.y<1);gates=gates.filter(g=>g.y<1&&!g.passed);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const t of texts){t.y-=dt*.07;t.life-=dt}texts=texts.filter(t=>t.life>0);shake*=Math.pow(.02,dt);updateHud()}
function rr(x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.roundRect(x,y,w,h,q)}
function drawSoldier(x,y,scale,enemy=false){ctx.save();ctx.translate(x,y);ctx.fillStyle=enemy?'#e94f57':'#2ba8ff';ctx.beginPath();ctx.arc(0,-scale*3.8,scale*3.1,0,6.3);ctx.fill();rr(-scale*3,-scale*1.6,scale*6,scale*7,scale*2);ctx.fill();ctx.fillStyle=enemy?'#7f1e27':'#0a5eaa';rr(scale*2,-scale*1,scale*6,scale*1.8,scale);ctx.fill();ctx.restore()}
function draw(){ctx.save();const sx=(rng()-.5)*shake,sy=(rng()-.5)*shake;ctx.translate(sx,sy);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#07121f');grad.addColorStop(.62,'#0c2234');grad.addColorStop(1,'#0b1928');ctx.fillStyle=grad;ctx.fillRect(-10,-10,W+20,H+20);
  ctx.strokeStyle='rgba(80,166,214,.07)';ctx.lineWidth=1;const grid=Math.max(34,Math.min(W,H)*.07);for(let y=(levelTime*40)%grid;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let x=0;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}
  const laneW=Math.min(W*.92,900);ctx.fillStyle='rgba(67,201,255,.035)';ctx.fillRect((W-laneW)/2,0,laneW,H);ctx.strokeStyle='rgba(255,255,255,.06)';ctx.beginPath();ctx.moveTo(W*.5,0);ctx.lineTo(W*.5,H);ctx.stroke();
  for(const g of gates){const x=(g.x-g.w/2)*W,y=(g.y-g.h/2)*H,w=g.w*W,h=g.h*H;ctx.fillStyle=g.active?'rgba(67,255,164,.14)':'rgba(78,176,255,.10)';ctx.strokeStyle=g.active?'#58f3a1':'#43bfff';ctx.lineWidth=2;rr(x,y,w,h,13);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font=`900 ${clamp(w*.09,12,20)}px system-ui`;ctx.textAlign='center';ctx.fillText(gateLabel(g),g.x*W,g.y*H+4);const pw=w*.7,ph=4,prog=clamp(g.progress/g.charge,0,1);ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(g.x*W-pw/2,y+h-11,pw,ph);ctx.fillStyle=g.active?'#62f7a8':'#55c7ff';ctx.fillRect(g.x*W-pw/2,y+h-11,pw*prog,ph)}
  for(const b of bullets){ctx.fillStyle=frenzyTime>0?'#9ce8ff':'#f5fbff';ctx.beginPath();ctx.arc(b.x*W,b.y*H,Math.max(2.2,Math.min(W,H)*.004),0,6.3);ctx.fill()}
  for(const e of enemies){drawSoldier(e.x*W,e.y*H,Math.max(1.3,e.r/8),true);if(e.elite){ctx.strokeStyle='#ffb24d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x*W,e.y*H,e.r+5,0,6.3);ctx.stroke()}}
  if(boss){const x=boss.x*W,y=boss.y*H;ctx.save();ctx.translate(x,y);ctx.fillStyle='#a42631';rr(-boss.r,-boss.r*.52,boss.r*2,boss.r*1.04,boss.r*.22);ctx.fill();ctx.fillStyle='#6d1821';rr(-boss.r*.65,-boss.r*.76,boss.r*1.3,boss.r*.55,boss.r*.2);ctx.fill();ctx.fillStyle='#c94349';rr(boss.r*.15,-boss.r*.52,boss.r*1.18,boss.r*.18,8);ctx.fill();ctx.restore();const bw=Math.min(W*.48,360),by=y-boss.r-26;ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(W/2-bw/2,by,bw,8);ctx.fillStyle='#ff5e64';ctx.fillRect(W/2-bw/2,by,bw*clamp(boss.hp/boss.maxHp,0,1),8);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 12px system-ui';ctx.fillText(boss.name,W/2,by-7)}
  const shown=Math.min(player.troops,30),cols=Math.min(10,Math.ceil(Math.sqrt(shown*1.6))),size=clamp(Math.min(W,H)*.0058,2.1,3.8);for(let i=0;i<shown;i++){const row=Math.floor(i/cols),col=i%cols,used=Math.min(cols,shown-row*cols),cx=(col-(used-1)/2)*size*5.2;drawSoldier(player.x*W+cx,.82*H+row*size*4.4,size,false)}ctx.fillStyle='#fff';ctx.font=`950 ${clamp(Math.min(W,H)*.038,18,30)}px system-ui`;ctx.textAlign='center';ctx.fillText(`${player.troops}`,player.x*W,.91*H);ctx.font=`800 ${clamp(Math.min(W,H)*.018,10,13)}px system-ui`;ctx.fillStyle='#76cfff';ctx.fillText(`SQUAD  •  DMG ${player.damage.toFixed(1)}  •  ${player.fireRate.toFixed(1)}/s  •  ARMOR ${player.armor}`,W/2,.94*H);
  if(frenzyTime>0){ctx.fillStyle='rgba(72,208,255,.08)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#72dcff';ctx.font=`950 ${clamp(Math.min(W,H)*.035,18,29)}px system-ui`;ctx.textAlign='left';ctx.fillText(`FRENZY ${frenzyTime.toFixed(1)}s`,18,H*.18)}else{const fw=Math.min(180,W*.32);ctx.fillStyle='#7e9db2';ctx.font='900 9px system-ui';ctx.textAlign='left';ctx.fillText('FRENZY',18,H*.17-7);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(18,H*.17,fw,6);ctx.fillStyle='#54cfff';ctx.fillRect(18,H*.17,fw*(frenzy/12),6)}
  for(const p of particles){ctx.globalAlpha=clamp(p.life*3,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*W,p.y*H,p.size,0,6.3);ctx.fill()}ctx.globalAlpha=1;for(const t of texts){ctx.globalAlpha=clamp(t.life*2,0,1);ctx.fillStyle=t.color;ctx.font=`900 ${t.size}px system-ui`;ctx.textAlign='center';ctx.fillText(t.text,t.x*W,t.y*H)}ctx.globalAlpha=1;ctx.restore()}
function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();captureFrames++;if(!captureMode||captureFrames<190)requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setPointer(e){const r=canvas.getBoundingClientRect();pointerX=clamp((e.clientX-r.left)/r.width,.05,.95)}canvas.addEventListener('pointerdown',e=>{pointerActive=true;setPointer(e);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(pointerActive||e.pointerType==='mouse')setPointer(e)});canvas.addEventListener('pointerup',()=>pointerActive=false);addEventListener('keydown',e=>{keys[e.key]=true;if(state==='menu'&&(e.key===' '||e.key==='Enter'))startRun()});addEventListener('keyup',e=>keys[e.key]=false);playBtn.onclick=()=>startRun();retryBtn.onclick=()=>startRun();soundBtn.onclick=()=>{sound=!sound;soundBtn.textContent=sound?'♪':'×';if(sound)initAudio()};
const q=query;if(q.get('demo')==='1'){menu.classList.remove('visible');startRun(Number(q.get('seed')||42));pointerX=.32;if(!captureMode)setInterval(()=>{pointerX=.18+rng()*.64},1800)}
